version: '3.4'

services:
  config-server:
    image: maven:3.8.4-openjdk-17-slim
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8889:8889
    working_dir: /server
    command: sh -c "cd /server && mvn clean && mvn spring-boot:run"
    user: root
    volumes:
      - ./config-server:/server
    networks:
      - UN-network

  discovery-server:
    image: maven:3.8.4-openjdk-17-slim
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8761:8761
    working_dir: /server
    command: sh -c "cd /server && mvn clean && mvn spring-boot:run"
    user: root
    volumes:
      - ./discovery-server:/server
    depends_on:
      - config-server
    networks:
      - UN-network
  # user-services:
  #   image: maven:3.8.4-openjdk-17-slim
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - ./user-service:/app
  #   working_dir: /app
  #   command: sh -c "cd /app && mvn clean && mvn spring-boot:run"
  #   networks:
  #     - UN-network
  product-service:
    image: maven:3.8.4-openjdk-17-slim
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./product-service:/app
    working_dir: /app
    command: sh -c "cd /app && mvn clean && mvn spring-boot:run"
    networks:
      - UN-network

networks:
  UN-network:
    driver: bridge