server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/products/**
