server:
  port: 8889
  servlet:
    context-path: /config
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      enabled: false
      server:
        native:
          search-locations: .
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka